### ISSUE TITLE
localhost:3000?

### ISSUE THREAD

**Issue by Archmonoculus** [RussianWaffles/mewbot-autocatcher#11]
localhost:3000? is it a website... and if so is there a link because my browser wont bring me to a page.
Any help would be greatly appreciated, thx!

**Comment by purvadeep07** [comment]
u need setup program before visiting localhost:3000

**Comment by purvadeep07** [comment]
> localhost:3000? is it a website... and if so is there a link because my browser wont bring me to a page.
> Any help would be greatly appreciated, thx!

u need setup program before visiting localhost:3000

**Comment by Archmonoculus** [comment]
yeah but like how do you do that? do you need to run it out of a custom api?

**Comment by purvadeep** [comment]
> yeah but like how do you do that? do you need to run it out of a custom API?

u just need to type localhost:3000 in any browser u use  after u run the program
