### ISSUE TITLE
missing fishing feature                                    

### ISSUE THREAD

**Issue by purvadeep** [RussianWaffles/mewbot-autocatcher#12]
there is a feature of mewbot called fishing when u  enter the cmd  ;fish u can see in the image
![Capture](https://user-images.githubusercontent.com/78193122/106234948-b7144800-621f-11eb-83cd-9c2b09d74d0a.PNG)
hope u can add 
a feature called auto fish

**Comment by RussianWaffles** [comment]
This project is not actively being worked on.
