### ISSUE TITLE
Token issue

### ISSUE THREAD

**Issue by StecemDamce** [RussianWaffles/mewbot-autocatcher#14]
When i open cmd, install all what need and print npm start, after i join localhost:3000 and print token, after that problem
Full error code:

 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mewbot-autocatcher@1.3.1~prestart: mewbot-autocatcher@1.3.1
6 info lifecycle mewbot-autocatcher@1.3.1~start: mewbot-autocatcher@1.3.1
7 verbose lifecycle mewbot-autocatcher@1.3.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle mewbot-autocatcher@1.3.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\AbcDe\Desktop\build (1)\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\AbcDe\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\AbcDe\AppData\Local\Programs\Python\Python39\;"C:\Users\AbcDe\AppData\Local\Microsoft\WindowsApps;C:\Users\AbcDe\AppData\Local\Programs\Python\Python39\Scripts";C:\Users\AbcDe\AppData\Roaming\npm
9 verbose lifecycle mewbot-autocatcher@1.3.1~start: CWD: C:\Users\AbcDe\Desktop\build (1)
10 silly lifecycle mewbot-autocatcher@1.3.1~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle mewbot-autocatcher@1.3.1~start: Returned: code: 1  signal: null
12 info lifecycle mewbot-autocatcher@1.3.1~start: Failed to exec start script
13 verbose stack Error: mewbot-autocatcher@1.3.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid mewbot-autocatcher@1.3.1
15 verbose cwd C:\Users\AbcDe\Desktop\build (1)
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error mewbot-autocatcher@1.3.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the mewbot-autocatcher@1.3.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by RussianWaffles** [comment]
It would appear something is wrong with either node itself or just the installation of the program, try the following steps:
1. Delete the `node_modules` folder inside the program directory
1. Open a terminal inside the program directory(you may have to start it as an administrator if you get permission errors)
1. Run `npm cache clean --force`
1. Run `npm install`
1. Try running the program again with `npm start`
<br>
If the above solution does not work you may want to upgrade your node installation which can be done with the following steps:

1. Open a terminal(you may have to start it as an administrator if you get permission errors)
1. Run `npm install -g n`
1. Run `n stable upgrade`
1. Repeat steps in previous list

**Comment by StecemDamce** [comment]
> It would appear something is wrong with either node itself or just the installation of the program, try the following steps:
> 
> 1. Delete the `node_modules` folder inside the program directory
> 2. Open a terminal inside the program directory(you may have to start it as an administrator if you get permission errors)
> 3. Run `npm cache clean --force`
> 4. Run `npm install`
> 5. Try running the program again with `npm start`
> 
> 
> If the above solution does not work you may want to upgrade your node installation which can be done with the following steps:
> 1. Open a terminal(you may have to start it as an administrator if you get permission errors)
> 2. Run `npm install -g n`
> 3. Run `n stable upgrade`
> 4. Repeat steps in previous list

Bro idk what happened, today i install again your program, and all work. But now spam doesnt work, i print channel id, prefix, but spam doesnt work

**Comment by RussianWaffles** [comment]
This may occur for multiple reasons, ensure the following:
* You have added either the second or third bot(the first bot will not be used for spam)
* You have enabled the spam checkbox in the server specific config
* You have enabled the global spam checkbox in the options window
* The spam.txt file is present and not blank
* The spam bots are in the required servers
* The channel ID given is valid

**Comment by StecemDamce** [comment]
> This may occur for multiple reasons, ensure the following:
> 
> * You have added either the second or third bot(the first bot will not be used for spam)
> * You have enabled the spam checkbox in the server specific config
> * You have enabled the global spam checkbox in the options window
> * The spam.txt file is present and not blank
> * The spam bots are in the required servers
> * The channel ID given is valid

Yes, i forgot add second bot. Now all ok, thx for help! :)
