### ISSUE TITLE
Spam issue

### ISSUE THREAD

**Issue by StecemDamce** [RussianWaffles/mewbot-autocatcher#15]
Couldn't send spam message to undefined
Server spam has been disabled

I enable spam feature for server, after click spam in down, and i see that error. Spam checkbox turned to false.

**Comment by RussianWaffles** [comment]
Please ensure the following:
* The channel ID you provided is valid
* The spam bot has permission to send messages
* The spam bot is in the required server

**Comment by StecemDamce** [comment]
Fixex, i just change server, idk maybe problems with discord
