### ISSUE TITLE
Auto catch delay issue

### ISSUE THREAD

**Issue by StecemDamce** [RussianWaffles/mewbot-autocatcher#17]
**Describe the bug**
The fact is that the delay of auto catch does not work, and this greatly affects the secrecy of actions

**To Reproduce**
1. Go to `localhost:3000`
2. Click on `server`
3. Scroll down to `autocatch delay`
4. Change value of `autocatch delay`
5. See that ``nothing happens``

**Expected behavior**
I expected auto catching to have a delay that would work

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/85005476/120230047-28f4b080-c257-11eb-9a9f-24c55c2a68f8.png)
![Unnamed](https://user-images.githubusercontent.com/85005476/120230244-943e8280-c257-11eb-8010-faf22ba45a1e.png)

**Comment by RussianWaffles** [comment]
Found the issue for autocatch delay, a fix can be applied manually by editing line 480 of `index.js` from:
```js
if(serverconfig && serverconfig.delay) await delay(config.delay * 1000);
```
to
```js
if(serverconfig && serverconfig.delay) await delay(serverconfig.delay * 1000);
```

**Comment by StecemDamce** [comment]
> Found the issue for autocatch delay, a fix can be applied manually by editing line 480 of `index.js` from:
> 
> ```js
> if(serverconfig && serverconfig.delay) await delay(config.delay * 1000);
> ```
> 
> to
> 
> ```js
> if(serverconfig && serverconfig.delay) await delay(serverconfig.delay * 1000);
> ```

Hello, autocatch delay fixed. But, can i transform seconds in miliseconds. Like, i want place 2.5 seconds, but i think that break script.

**Comment by RussianWaffles** [comment]
If it has an issue with decimals you can change line 480 of `index.js` into
```js
if(serverconfig && serverconfig.delay) await delay(serverconfig.delay);
```
and the input will turn into milliseconds, 2.5 seconds is 2500 milliseconds.

**Comment by StecemDamce** [comment]
> If it has an issue with decimals you can change line 480 of `index.js` into
> 
> ```js
> if(serverconfig && serverconfig.delay) await delay(serverconfig.delay);
> ```
> 
> and the input will turn into milliseconds, 2.5 seconds is 2500 milliseconds.

Thx
