### ISSUE TITLE
Does not catch shinies or Legendary Pokemon

### ISSUE THREAD

**Issue by AdesaCore** [RussianWaffles/mewbot-autocatcher#4]
[bot1] Unknown Pokemon: http://mewbot.skylarr.me:5001/image?pokemon=shiny/173-0-.png - fffffffffffffe3ffe3ff80fc003c043c1e3e187f087f007e007e00fe00ff89f
[Command] Unrecognised Pokemon Reported

**Comment by AdesaCore** [comment]
Mr.Rime is also Mr Rime in the bot with no "." 
Mime Jr. has a period. 
Kabuto registers as an unknown pokemon.

**Comment by AdesaCore** [comment]
Shiny Cleffa came up as ":star2:cleffa"

**Comment by RussianWaffles** [comment]
Fixed in latest commit.
[Commit](https://github.com/RussianWaffles/mewbot-autocatcher/commit/6e4c88fa8e7b6cd6992665a9fe915d4cc34a8dd0)
