### ISSUE TITLE
error setting up the program 

### ISSUE THREAD

**Issue by Jin-requiem** [RussianWaffles/mewbot-autocatcher#5]
so im trying to set up this program in powershell sorry im not the brightest in tech but obviously im doing something wrong this is what i get

pm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\dont touch da child\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\dont touch da child\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dont touch da child\AppData\Roaming\npm-cache\_logs\2020-07-17T00_52_14_849Z-debug.log
PS C:\Users\dont touch da child>

**Comment by purvadeep07** [comment]
u

> so im trying to set up this program in powershell sorry im not the brightest in tech but obviously im doing something wrong this is what i get
> 
> pm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path C:\Users\dont touch da child\package.json
> npm ERR! errno -4058
> npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\dont touch da child\package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\dont touch da child\AppData\Roaming\npm-cache_logs\2020-07-17T00_52_14_849Z-debug.log
> PS C:\Users\dont touch da child>

u need to locate your folder in power shell
