### ISSUE TITLE
confusion 

### ISSUE THREAD

**Issue by ofui** [RussianWaffles/mewbot-autocatcher#6]
do you mind explaining it  little better i cant even get past the first main part

**Comment by OreoLamb** [comment]
you will need to download node.js then do the steps

**Comment by OreoLamb** [comment]
basically, first download the build, unzip it and open command prompt in it, do the commands mentioned, at then go to localhost:3000 on your browser, there will be a GUI, next open discord on chrome and open developer tools by Shift + CTRL + J and go to console tab, then copy the script and paste it and click enter,  then you will get a string of characters, that is your token, then go to the little avatar image and enter your token into the id, and then its plain sailing from there

**Comment by Sprizen9** [comment]
How to go to localhost:3000?? Is it a webSite?

**Comment by purvadeep07** [comment]
> How to go to localhost:3000?? Is it a webSite?

yes
open it after using npm start
