### ISSUE TITLE
Running more than 1

### ISSUE THREAD

**Issue by immortalkillroy** [RussianWaffles/mewbot-autocatcher#7]
Hello, and first of all thanks for making this nice tool and especially making it free, we appreciate it 

what is an easy way to set up a second instance of this on the same pc? changing the 3000 port in index.js gives me port already in use, etc

**Comment by RussianWaffles** [comment]
Hi, as of this time there is currently no simple way to change the port, however it can still be done by following the following steps

1. Inside `index.js` change line 601 from `app.listen(3000);` to `app.listen(<desired web port>);`
2. Inside `index.js` change line 539 from `server.listen(3001, async () => {` to `server.listen(<desired websocket port>, async () => {`
3. Inside `build/static/js/main. ... .chunk.js` find the line `"ws://"+window.location.hostname+":3001/"` and change it to `"ws://"+window.location.hostname+":<desired websocket port>/"`

After starting the bot with the following edits the web panel can now be accessed at `http://localhost:<desired web port>`
